<?php

namespace Container6vSnUlD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoral_ConnectorService extends Coral_CoreBundle_Tests_Resources_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'coral.connector' shared service.
     *
     * @return \Coral\CoreBundle\Service\Connector
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/Service/Connector.php';

        $container->services['coral.connector'] = $instance = new \Coral\CoreBundle\Service\Connector();

        $instance->addConnector(($container->privates['coral.connect.coral'] ?? $container->load('getCoral_Connect_CoralService')), 'coral');
        $instance->addConnector(($container->privates['coral.connect.stark'] ?? $container->load('getCoral_Connect_StarkService')), 'stark');
        $instance->addConnector(($container->privates['coral.connect.coral_uncached'] ?? $container->load('getCoral_Connect_CoralUncachedService')), 'coral_uncached');

        return $instance;
    }
}
