<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRYOzrxS\Coral_CoreBundle_Tests_Resources_app_AppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRYOzrxS/Coral_CoreBundle_Tests_Resources_app_AppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerRYOzrxS.legacy');

    return;
}

if (!\class_exists(Coral_CoreBundle_Tests_Resources_app_AppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerRYOzrxS\Coral_CoreBundle_Tests_Resources_app_AppKernelTestDebugContainer::class, Coral_CoreBundle_Tests_Resources_app_AppKernelTestDebugContainer::class, false);
}

return new \ContainerRYOzrxS\Coral_CoreBundle_Tests_Resources_app_AppKernelTestDebugContainer([
    'container.build_hash' => 'RYOzrxS',
    'container.build_id' => 'b95f81c0',
    'container.build_time' => 1661765220,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRYOzrxS');
